#!/bin/bash
module unload python
module load python/3.5.1
export PYTHONPATH=/nfs/sw/python/python-3.5.1/bin:/gpfs/commons/groups/imielinski_lab/lib/python-3.5.1/site-packages:/nfs/sw/python/python-3.5.1/lib/python3.5/site-packages

